add searchProfile and viewProfile for feature my-account
jurodriguezf/statera pull request #16
Opened 2022-04-24 13:35 UTC by bdleons

por favor revisen si que lo hice esta bien y no rompí nada

2022-04-24 19:49 UTC, mondracode commented on statera-backend/cmd/api/domain/db/searchProfile.go
> +		fmt.Println("Record No Found. " + err.Error())
Debería ser "Record not found."

2022-04-24 19:50 UTC, mondracode commented on statera-backend/cmd/api/domain/routers/register.go
>  	if found == true {
Sé que eso no lo tocó usted, pero el `== true` es innecesario

2022-04-24 19:52 UTC, bdleons commented on statera-backend/cmd/api/domain/db/searchProfile.go
> +		fmt.Println("Record No Found. " + err.Error())
ok ya lo corrijo

2022-04-24 19:52 UTC, mondracode commented on statera-backend/cmd/api/domain/db/searchProfile.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
Dejar ese 15 suelto  es mala práctica porque disminuye la legibilidad. Lo recomendable es hacer una constante llamada SEARCH_TIMEOUT o algo así, y asignarle el 15. Esto es para que la persona que venga a leer el código pueda entender qué hace cada cifra en lugar de ver números por ahí volando.

2022-04-24 19:53 UTC, mondracode commented on statera-backend/cmd/api/domain/db/searchProfile.go
> +	profile.Password = ""
Para qué estamos asignando esto?

2022-04-24 19:54 UTC, mondracode commented on statera-backend/cmd/server/server.go
> -	router.GET("/ping", func(c *gin.Context) {
Yo dejaría el ping convertido a mux porque es la manera más rápida de testear si tenemos la API funcionando.

2022-04-24 19:55 UTC, bdleons commented on statera-backend/cmd/api/domain/db/searchProfile.go
> +	profile.Password = ""
FindOne retorna toda la información del usuario, no queremos retornar su contraseña en el json

2022-04-24 20:09 UTC, jgonzalezar commented on statera-backend/cmd/api/domain/routers/register.go
>  	if found == true {
es verdad, se puede poner !found.

2022-04-24 20:10 UTC, jgonzalezar commented on statera-backend/cmd/api/domain/db/searchProfile.go
> +	profile.Password = ""
y el profile.Password = ""
lo que hace es vaciar el campo de profile para no guardarlo ya que por buenas prácticas de seguridad informática, no deberíamos guardar los passwords de los usuarios, solo los encriptados.

2022-04-24 20:11 UTC, jgonzalezar commented on statera-backend/cmd/server/server.go
> -	router.GET("/ping", func(c *gin.Context) {
me parece.

2022-04-25 00:55 UTC, mondracode approved these changes

2022-04-25 00:56 UTC, mondracode commented on statera-backend/cmd/api/domain/db/searchProfile.go
> +var SearchTimeout time.Duration = 15
una **constante**

2022-04-25 00:56 UTC, mondracode requested changes
pls cambiar la constante

2022-04-25 02:26 UTC, bdleons commented on statera-backend/cmd/api/domain/db/searchProfile.go
> +var SearchTimeout time.Duration = 15
Ok, ya lo cambio

2022-04-25 19:44 UTC, mondracode approved these changes

2022-04-25 19:44 UTC, merged